default:
  navigation:
    - title: Cruise
      subtitle: Балуем себя
      url: /t/cruise
      items:
        - :title: юбки
          :url: /t/cruise/skirts
        - :title: брюки
          :url: /t/cruise/trousers
        - :title: платья
          :url: /t/cruise/dresses
        - :title: рубашки
          :url: /t/cruise/shirts-and-blouses
        - :title: шорты
          :url: /t/cruise/shorts
        - :title: куртки и ветровки
          :url: /t/cruise/jackets-and-coats
      promo_banners:
        - subtitle: New collection
          title: Лето 2020
          url: /t/summer-collection
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Предзаказ
          title: Индивидуальный заказ
          url: /t/pre-orders
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Classic
      subtitle: Ваш базовый гардероб
      url: /t/classic
      items:
        - :title: Рубашки
          :url: /t/classic/shirts
        - :title: Брюки
          :url: /t/classic/pants
        - :title: Платья
          :url: /t/classic/dresses
        - :title: куртки и ветровки
          :url: /t/classic/jackets-and-coats
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/summer-collection
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Office
      subtitle: Деловая одежда
      url: /t/office
      items:
        - :title: Юбки
          :url: /t/office/skirts
        - :title: Рубашки
          :url: /t/office/shirts
        - :title: Топы
          :url: /t/office/tops
        - :title: пиджаки
          :url: /t/sportswear/jackets
        - :title: Брюки
          :url: /t/office/pants
      promo_banners:
        - subtitle: New collection
          title: Summer 2020
          url: /t/summer-collection
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers
          image: 'meganav/promo_banner_right-third-category.jpg'
